// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: protocol/proto/okxorderbook.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OkxOrderBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstID       string      `protobuf:"bytes,1,opt,name=instID,proto3" json:"instID,omitempty"`
	InstType     string      `protobuf:"bytes,2,opt,name=instType,proto3" json:"instType,omitempty"`
	Bids         []*OkxOrder `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks         []*OkxOrder `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	UpdateTimeMs int64       `protobuf:"varint,5,opt,name=updateTimeMs,proto3" json:"updateTimeMs,omitempty"`
	SeqID        int64       `protobuf:"varint,6,opt,name=seqID,proto3" json:"seqID,omitempty"`
}

func (x *OkxOrderBook) Reset() {
	*x = OkxOrderBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_okxorderbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkxOrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkxOrderBook) ProtoMessage() {}

func (x *OkxOrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_okxorderbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkxOrderBook.ProtoReflect.Descriptor instead.
func (*OkxOrderBook) Descriptor() ([]byte, []int) {
	return file_protocol_proto_okxorderbook_proto_rawDescGZIP(), []int{0}
}

func (x *OkxOrderBook) GetInstID() string {
	if x != nil {
		return x.InstID
	}
	return ""
}

func (x *OkxOrderBook) GetInstType() string {
	if x != nil {
		return x.InstType
	}
	return ""
}

func (x *OkxOrderBook) GetBids() []*OkxOrder {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OkxOrderBook) GetAsks() []*OkxOrder {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *OkxOrderBook) GetUpdateTimeMs() int64 {
	if x != nil {
		return x.UpdateTimeMs
	}
	return 0
}

func (x *OkxOrderBook) GetSeqID() int64 {
	if x != nil {
		return x.SeqID
	}
	return 0
}

type OkxOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Size  float64 `protobuf:"fixed64,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *OkxOrder) Reset() {
	*x = OkxOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_okxorderbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OkxOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkxOrder) ProtoMessage() {}

func (x *OkxOrder) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_okxorderbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkxOrder.ProtoReflect.Descriptor instead.
func (*OkxOrder) Descriptor() ([]byte, []int) {
	return file_protocol_proto_okxorderbook_proto_rawDescGZIP(), []int{1}
}

func (x *OkxOrder) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OkxOrder) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_protocol_proto_okxorderbook_proto protoreflect.FileDescriptor

var file_protocol_proto_okxorderbook_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x6b, 0x78, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x0c, 0x4f, 0x6b, 0x78, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6e, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4f, 0x6b, 0x78, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4f, 0x6b, 0x78, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65,
	0x71, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x44,
	0x22, 0x34, 0x0a, 0x08, 0x4f, 0x6b, 0x78, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_proto_okxorderbook_proto_rawDescOnce sync.Once
	file_protocol_proto_okxorderbook_proto_rawDescData = file_protocol_proto_okxorderbook_proto_rawDesc
)

func file_protocol_proto_okxorderbook_proto_rawDescGZIP() []byte {
	file_protocol_proto_okxorderbook_proto_rawDescOnce.Do(func() {
		file_protocol_proto_okxorderbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_okxorderbook_proto_rawDescData)
	})
	return file_protocol_proto_okxorderbook_proto_rawDescData
}

var file_protocol_proto_okxorderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_proto_okxorderbook_proto_goTypes = []interface{}{
	(*OkxOrderBook)(nil), // 0: OkxOrderBook
	(*OkxOrder)(nil),     // 1: OkxOrder
}
var file_protocol_proto_okxorderbook_proto_depIdxs = []int32{
	1, // 0: OkxOrderBook.bids:type_name -> OkxOrder
	1, // 1: OkxOrderBook.asks:type_name -> OkxOrder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_proto_okxorderbook_proto_init() }
func file_protocol_proto_okxorderbook_proto_init() {
	if File_protocol_proto_okxorderbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_okxorderbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkxOrderBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proto_okxorderbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OkxOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_okxorderbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_okxorderbook_proto_goTypes,
		DependencyIndexes: file_protocol_proto_okxorderbook_proto_depIdxs,
		MessageInfos:      file_protocol_proto_okxorderbook_proto_msgTypes,
	}.Build()
	File_protocol_proto_okxorderbook_proto = out.File
	file_protocol_proto_okxorderbook_proto_rawDesc = nil
	file_protocol_proto_okxorderbook_proto_goTypes = nil
	file_protocol_proto_okxorderbook_proto_depIdxs = nil
}
